#!/bin/bash

rm -f Config.hpp
echo "// this file is automatically generated by mkconfig.sh" > Config.hpp
echo "#define CONFIG_TARGET \"$1\"" >> Config.hpp
echo "#define CONFIG_DATE \"$(LC_TIME=en_US date -u "+%d-%b-%Y %R")\"" >> Config.hpp

echo "#define CONFIG_REVISION \"$(git rev-parse HEAD)\"" >> Config.hpp

dirty=0

if ! git diff-files --quiet
then
	dirty=1
fi
if ! git diff-index --cached --quiet HEAD
then
	dirty=1
fi

if [ $dirty = 1 ]
then
	echo "#define CONFIG_DIRTY" >> Config.hpp
fi

